services:
  pocketbase:
    image: chanceium/ebookbase:latest
    container_name: pocketbase
    restart: unless-stopped
    user: 0:0
    ports:
      - "8090:8090"
    volumes:
      - ebookshelf:/pb_data

  ebookshelf:
    image: chanceium/ebookshelf:latest
    container_name: ebookshelf
    restart: unless-stopped
    ports:
      - "8091:3001"
    environment:
      - NODE_ENV=production

volumes:
  ebookshelf:
